#iboardSheet
public_gsheets_url = "https://docs.google.com/spreadsheets/d/1zT1qwlscrYk6m53vl-OD1zxP-LftchFJt1L5DflccJ4/edit?usp=sharing"
# streamlit_app.py
# .streamlit/secrets.toml
AWS_ACCESS_KEY_ID = "AKIAWUMYJITKDSE5R45R"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-2"

